import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-private-equity-management-fee-offset-audit",
  "engine": "recovery",
  "title": "Private Equity Management Fee Offset Audit",
  "shortTitle": "Private Equity Management Fee Offset Audit",
  "tagline": "Recalculate management fees and contractual offsets to protect limited partners from excess fund charges.",
  "industry": "Private Markets Finance",
  "buyer": "Limited partners and fund finance teams",
  "uiPort": 4673,
  "apiPort": 5673,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Private Equity Management Fee Offset Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect limited partnership agreements, commitments, invested capital, portfolio fees, transaction fees, monitoring fees, offsets, waivers, invoices, capital accounts, and statements in one accountable workflow. Recalculate management fees and contractual offsets to protect limited partners from excess fund charges.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Private Equity Management Fee Offset Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("lpa-fee-terms","PEM01","LPA fee terms","Execute lpa fee terms using limited partnership agreements, commitments, invested capital, portfolio fees, transaction fees, monitoring fees, offsets, waivers, invoices, capital accounts, and statements.","Produce a governed lpa fee terms decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fund / Portfolio Company","text","Fund / Portfolio Company · Standard Case"],["caseReference","LPA fee terms Reference","text","PEM01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",920000],["supportedAmount","Evidence-Supported Amount","currency",772800],["domainDriver","Offset Source","select","Transaction fee",["Transaction fee","Monitoring fee","Director fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["LPA fee terms case","Investor commitment registry case","Investment period control case","Fee base calculation case","Step-down calculation case"]}),
feature("investor-commitment-registry","PEM02","Investor commitment registry","Execute investor commitment registry using limited partnership agreements, commitments, invested capital, portfolio fees, transaction fees, monitoring fees, offsets, waivers, invoices, capital accounts, and statements.","Produce a governed investor commitment registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fund / Portfolio Company","text","Fund / Portfolio Company · Standard Case"],["caseReference","Investor commitment registry Reference","text","PEM02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",920000],["supportedAmount","Evidence-Supported Amount","currency",772800],["domainDriver","Offset Source","select","Transaction fee",["Transaction fee","Monitoring fee","Director fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["LPA fee terms case","Investor commitment registry case","Investment period control case","Fee base calculation case","Step-down calculation case"]}),
feature("investment-period-control","PEM03","Investment period control","Execute investment period control using limited partnership agreements, commitments, invested capital, portfolio fees, transaction fees, monitoring fees, offsets, waivers, invoices, capital accounts, and statements.","Produce a governed investment period control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fund / Portfolio Company","text","Fund / Portfolio Company · Standard Case"],["caseReference","Investment period control Reference","text","PEM03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",920000],["supportedAmount","Evidence-Supported Amount","currency",772800],["domainDriver","Offset Source","select","Transaction fee",["Transaction fee","Monitoring fee","Director fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["LPA fee terms case","Investor commitment registry case","Investment period control case","Fee base calculation case","Step-down calculation case"]}),
feature("fee-base-calculation","PEM04","Fee base calculation","Execute fee base calculation using limited partnership agreements, commitments, invested capital, portfolio fees, transaction fees, monitoring fees, offsets, waivers, invoices, capital accounts, and statements.","Produce a governed fee base calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fund / Portfolio Company","text","Fund / Portfolio Company · Standard Case"],["caseReference","Fee base calculation Reference","text","PEM04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",920000],["supportedAmount","Evidence-Supported Amount","currency",772800],["domainDriver","Offset Source","select","Transaction fee",["Transaction fee","Monitoring fee","Director fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["LPA fee terms case","Investor commitment registry case","Investment period control case","Fee base calculation case","Step-down calculation case"]}),
feature("step-down-calculation","PEM05","Step-down calculation","Execute step-down calculation using limited partnership agreements, commitments, invested capital, portfolio fees, transaction fees, monitoring fees, offsets, waivers, invoices, capital accounts, and statements.","Produce a governed step-down calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fund / Portfolio Company","text","Fund / Portfolio Company · Standard Case"],["caseReference","Step-down calculation Reference","text","PEM05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",920000],["supportedAmount","Evidence-Supported Amount","currency",772800],["domainDriver","Offset Source","select","Transaction fee",["Transaction fee","Monitoring fee","Director fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["LPA fee terms case","Investor commitment registry case","Investment period control case","Fee base calculation case","Step-down calculation case"]}),
feature("transaction-fee-ingestion","PEM06","Transaction fee ingestion","Execute transaction fee ingestion using limited partnership agreements, commitments, invested capital, portfolio fees, transaction fees, monitoring fees, offsets, waivers, invoices, capital accounts, and statements.","Produce a governed transaction fee ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fund / Portfolio Company","text","Fund / Portfolio Company · Standard Case"],["caseReference","Transaction fee ingestion Reference","text","PEM06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",920000],["supportedAmount","Evidence-Supported Amount","currency",772800],["domainDriver","Offset Source","select","Transaction fee",["Transaction fee","Monitoring fee","Director fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["LPA fee terms case","Investor commitment registry case","Investment period control case","Fee base calculation case","Step-down calculation case"]}),
feature("monitoring-fee-ingestion","PEM07","Monitoring fee ingestion","Execute monitoring fee ingestion using limited partnership agreements, commitments, invested capital, portfolio fees, transaction fees, monitoring fees, offsets, waivers, invoices, capital accounts, and statements.","Produce a governed monitoring fee ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fund / Portfolio Company","text","Fund / Portfolio Company · Standard Case"],["caseReference","Monitoring fee ingestion Reference","text","PEM07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",920000],["supportedAmount","Evidence-Supported Amount","currency",772800],["domainDriver","Offset Source","select","Transaction fee",["Transaction fee","Monitoring fee","Director fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["LPA fee terms case","Investor commitment registry case","Investment period control case","Fee base calculation case","Step-down calculation case"]}),
feature("director-fee-ingestion","PEM08","Director fee ingestion","Execute director fee ingestion using limited partnership agreements, commitments, invested capital, portfolio fees, transaction fees, monitoring fees, offsets, waivers, invoices, capital accounts, and statements.","Produce a governed director fee ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fund / Portfolio Company","text","Fund / Portfolio Company · Standard Case"],["caseReference","Director fee ingestion Reference","text","PEM08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",920000],["supportedAmount","Evidence-Supported Amount","currency",772800],["domainDriver","Offset Source","select","Transaction fee",["Transaction fee","Monitoring fee","Director fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["LPA fee terms case","Investor commitment registry case","Investment period control case","Fee base calculation case","Step-down calculation case"]}),
feature("offset-percentage-calculation","PEM09","Offset percentage calculation","Execute offset percentage calculation using limited partnership agreements, commitments, invested capital, portfolio fees, transaction fees, monitoring fees, offsets, waivers, invoices, capital accounts, and statements.","Produce a governed offset percentage calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fund / Portfolio Company","text","Fund / Portfolio Company · Standard Case"],["caseReference","Offset percentage calculation Reference","text","PEM09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",920000],["supportedAmount","Evidence-Supported Amount","currency",772800],["domainDriver","Offset Source","select","Transaction fee",["Transaction fee","Monitoring fee","Director fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["LPA fee terms case","Investor commitment registry case","Investment period control case","Fee base calculation case","Step-down calculation case"]}),
feature("broken-deal-expense-review","PEM10","Broken-deal expense review","Execute broken-deal expense review using limited partnership agreements, commitments, invested capital, portfolio fees, transaction fees, monitoring fees, offsets, waivers, invoices, capital accounts, and statements.","Produce a governed broken-deal expense review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fund / Portfolio Company","text","Fund / Portfolio Company · Standard Case"],["caseReference","Broken-deal expense review Reference","text","PEM10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",920000],["supportedAmount","Evidence-Supported Amount","currency",772800],["domainDriver","Offset Source","select","Transaction fee",["Transaction fee","Monitoring fee","Director fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["LPA fee terms case","Investor commitment registry case","Investment period control case","Fee base calculation case","Step-down calculation case"]}),
feature("waiver-and-rebate-control","PEM11","Waiver and rebate control","Execute waiver and rebate control using limited partnership agreements, commitments, invested capital, portfolio fees, transaction fees, monitoring fees, offsets, waivers, invoices, capital accounts, and statements.","Produce a governed waiver and rebate control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fund / Portfolio Company","text","Fund / Portfolio Company · Standard Case"],["caseReference","Waiver and rebate control Reference","text","PEM11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",920000],["supportedAmount","Evidence-Supported Amount","currency",772800],["domainDriver","Offset Source","select","Transaction fee",["Transaction fee","Monitoring fee","Director fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["LPA fee terms case","Investor commitment registry case","Investment period control case","Fee base calculation case","Step-down calculation case"]}),
feature("capital-account-allocation","PEM12","Capital account allocation","Execute capital account allocation using limited partnership agreements, commitments, invested capital, portfolio fees, transaction fees, monitoring fees, offsets, waivers, invoices, capital accounts, and statements.","Produce a governed capital account allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fund / Portfolio Company","text","Fund / Portfolio Company · Standard Case"],["caseReference","Capital account allocation Reference","text","PEM12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",920000],["supportedAmount","Evidence-Supported Amount","currency",772800],["domainDriver","Offset Source","select","Transaction fee",["Transaction fee","Monitoring fee","Director fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["LPA fee terms case","Investor commitment registry case","Investment period control case","Fee base calculation case","Step-down calculation case"]}),
feature("quarterly-statement-audit","PEM13","Quarterly statement audit","Execute quarterly statement audit using limited partnership agreements, commitments, invested capital, portfolio fees, transaction fees, monitoring fees, offsets, waivers, invoices, capital accounts, and statements.","Produce a governed quarterly statement audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fund / Portfolio Company","text","Fund / Portfolio Company · Standard Case"],["caseReference","Quarterly statement audit Reference","text","PEM13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",920000],["supportedAmount","Evidence-Supported Amount","currency",772800],["domainDriver","Offset Source","select","Transaction fee",["Transaction fee","Monitoring fee","Director fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["LPA fee terms case","Investor commitment registry case","Investment period control case","Fee base calculation case","Step-down calculation case"]}),
feature("gp-correction-workflow","PEM14","GP correction workflow","Execute gp correction workflow using limited partnership agreements, commitments, invested capital, portfolio fees, transaction fees, monitoring fees, offsets, waivers, invoices, capital accounts, and statements.","Produce a governed gp correction workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fund / Portfolio Company","text","Fund / Portfolio Company · Standard Case"],["caseReference","GP correction workflow Reference","text","PEM14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",920000],["supportedAmount","Evidence-Supported Amount","currency",772800],["domainDriver","Offset Source","select","Transaction fee",["Transaction fee","Monitoring fee","Director fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["LPA fee terms case","Investor commitment registry case","Investment period control case","Fee base calculation case","Step-down calculation case"]}),
feature("fund-investor-analytics","PEM15","Fund investor analytics","Execute fund investor analytics using limited partnership agreements, commitments, invested capital, portfolio fees, transaction fees, monitoring fees, offsets, waivers, invoices, capital accounts, and statements.","Produce a governed fund investor analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fund / Portfolio Company","text","Fund / Portfolio Company · Standard Case"],["caseReference","Fund investor analytics Reference","text","PEM15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",920000],["supportedAmount","Evidence-Supported Amount","currency",772800],["domainDriver","Offset Source","select","Transaction fee",["Transaction fee","Monitoring fee","Director fee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["LPA fee terms case","Investor commitment registry case","Investment period control case","Fee base calculation case","Step-down calculation case"]})
]);
